server:
  port: 8079

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8079/eureka/

spring:
  application:
    name: eureka

